### ISSUE TITLE
2023 ss update?

### ISSUE THREAD

**Issue by Vozf** [motzet/tum-exam-dates#1]

**Comment by motzet** [comment]
Now pushed!

**Comment by Vozf** [comment]
Thank you20:35, March 15, 2023, "MM (m²)" ***@***.***>:
Now pushed!

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail
